commandConfiguration:
  executor: Yosyp Andriyash
  rootPath: vendor/customercare/customercare/src/

  namespaceConfig:
    rootNamespace: CustomerCare\
    calculatePathNamespaceCommencingBy: customercare/customercare/src/

  pathSchema:
    __PackageRootPath__:
      Model:
        Application:
          __PackageApplicationEntityQueryPath__: []
          __PackageApplicationEntityCommandPath__: []
        Domain:
          __PackageDomainEntityPath__:
            Entity: []
            Exception: []
            Repository: []
            Service: []

  templates:
    read:

      query:
        template: 'Templates/Files/ApplicationReadQuery.template.php'
        suffix: 'Query'
        templateClassDispatcher: 'ApplicationReadQueryTemplate'
        dependencies: []
        use: [
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceRequest'
        ]

      response:
        template: 'Templates/Files/ApplicationReadResponse.template.php'
        suffix: 'Response'
        templateClassDispatcher: 'ApplicationReadResponseTemplate'
        dependencies: []
        use: [
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceResponse'
        ]

      service:
        template: 'Templates/Files/ApplicationReadService.template.php'
        suffix: 'Service'
        templateClassDispatcher: 'ApplicationReadServiceTemplate'
        dependencies: ['ApplicationReadQueryTemplate', 'ApplicationReadResponseTemplate', 'DomainEntityServiceTemplate', 'DomainEntityRepositoryTemplate']
        use: [
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceRequest',
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceResponse'
        ]

    command:
      command:
        template: 'Templates/Files/ApplicationCommandCommand.template.php'
        suffix: 'Command'
        templateClassDispatcher: 'ApplicationCommandCommandTemplate'
        dependencies: []
        use: [
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceRequest'
        ]

      response:
        template: 'Templates/Files/ApplicationCommandResponse.template.php'
        suffix: 'Response'
        templateClassDispatcher: 'ApplicationCommandResponseTemplate'
        dependencies: []
        use: [
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceResponse'
        ]

      service:
        template: 'Templates/Files/ApplicationCommandService.template.php'
        suffix: 'Service'
        templateClassDispatcher: 'ApplicationCommandServiceTemplate'
        dependencies: ['ApplicationCommandCommandTemplate', 'ApplicationCommandResponseTemplate', 'DomainEntityServiceTemplate', 'DomainEntityRepositoryTemplate']
        use: [
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceRequest',
          'SoftwareArchitecture\ModelLayer\ApplicationLayer\ApplicationServiceResponse'
        ]

    domain:
      repositoryInterface:
        template: 'Templates/Files/DomainEntityRepository.template.php'
        suffix: 'Repository'
        templateClassDispatcher: 'DomainEntityRepositoryTemplate'
        dependencies: ['DomainEntityTemplate', 'DomainEntityCollectionTemplate']
        use: []

      service:
        template: 'Templates/Files/DomainEntityService.template.php'
        suffix: 'DomainService'
        templateClassDispatcher: 'DomainEntityServiceTemplate'
        dependencies: ['DomainEntityRepositoryTemplate', 'DomainEntityTemplate']
        use: []

      entity:
        template: 'Templates/Files/DomainEntity.template.php'
        suffix: ''
        templateClassDispatcher: 'DomainEntityTemplate'
        dependencies: []
        use: []

      entityCollection:
        template: 'Templates/Files/DomainEntityCollection.template.php'
        suffix: 'Collection'
        templateClassDispatcher: 'DomainEntityCollectionTemplate'
        dependencies: []
        use: []